//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Family_Business.WMGS.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FamilyBusinessEntities : DbContext
    {
        public FamilyBusinessEntities()
            : base("name=FamilyBusinessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_AllocationBox> tbl_AllocationBox { get; set; }
        public virtual DbSet<tbl_OilType> tbl_OilType { get; set; }
        public virtual DbSet<tbl_AllProduct> tbl_AllProduct { get; set; }
        public virtual DbSet<tbl_ShopName> tbl_ShopName { get; set; }
        public virtual DbSet<tbl_Sale> tbl_Sale { get; set; }
        public virtual DbSet<tbl_EmpStatus> tbl_EmpStatus { get; set; }
        public virtual DbSet<tbl_Genders> tbl_Genders { get; set; }
        public virtual DbSet<tbl_Users> tbl_Users { get; set; }
        public virtual DbSet<tbl_DayName> tbl_DayName { get; set; }
        public virtual DbSet<tbl_EmpOffDay> tbl_EmpOffDay { get; set; }
        public virtual DbSet<tbl_AttendanceConfirm> tbl_AttendanceConfirm { get; set; }
        public virtual DbSet<tbl_ProcesedSalary> tbl_ProcesedSalary { get; set; }
        public virtual DbSet<tbl_EmpAttendance> tbl_EmpAttendance { get; set; }
        public virtual DbSet<tbl_EmpPersonalInfo> tbl_EmpPersonalInfo { get; set; }
    }
}
