//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Family_Business.WMGS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EmpPersonalInfo
    {
        public int Id { get; set; }
        public string EID { get; set; }
        public string EmpFirstName { get; set; }
        public string EmpLastName { get; set; }
        public string EmpPhone { get; set; }
        public string EmpEmail { get; set; }
        public string EmpAddress { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<bool> ConfirmStatus { get; set; }
        public Nullable<int> EmpGender { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<decimal> EmpPay { get; set; }
        public byte[] EmpPhoto { get; set; }
        public string Education { get; set; }
        public string EmpNominee { get; set; }
        public string EmpNomineePhone { get; set; }
        public string EmpShift { get; set; }
        public Nullable<System.Guid> Create_User { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.Guid> Edit_User { get; set; }
        public Nullable<System.DateTime> Edit_Date { get; set; }
    }
}
