//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Family_Business.WMGS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Sale
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<int> ShopID { get; set; }
        public Nullable<decimal> Cash { get; set; }
        public Nullable<decimal> Card { get; set; }
        public Nullable<decimal> Cash_Tax { get; set; }
        public Nullable<decimal> Card_Tax { get; set; }
        public Nullable<System.Guid> Create_User { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.Guid> Edit_User { get; set; }
        public Nullable<System.DateTime> Edit_Date { get; set; }
        public Nullable<decimal> Cash_Total { get; set; }
        public Nullable<decimal> Card_Total { get; set; }
    }
}
