//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Family_Business.WMGS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AllProduct
    {
        public int id { get; set; }
        public Nullable<int> ProductType_Id { get; set; }
        public int OilType_Id { get; set; }
        public string Product_Code { get; set; }
        public string Product_Name { get; set; }
        public Nullable<int> Product_Location_Id { get; set; }
        public string Product_Index { get; set; }
        public Nullable<System.Guid> Create_User { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.Guid> Edit_User { get; set; }
        public Nullable<System.DateTime> Edit_Date { get; set; }
        public Nullable<int> FragranceType { get; set; }
    }
}
