//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Family_Business.WMGS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EmpAttendance
    {
        public int Id { get; set; }
        public string EID { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public Nullable<System.DateTime> AttendanceDate { get; set; }
        public Nullable<System.DateTime> AttendanceFromDate { get; set; }
        public Nullable<System.DateTime> AttendanceToDate { get; set; }
        public Nullable<int> WeekNumber { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<System.TimeSpan> In_Time { get; set; }
        public Nullable<System.TimeSpan> Out_Time { get; set; }
        public Nullable<decimal> Total_Hour { get; set; }
        public string Status { get; set; }
        public string Attendance_Day { get; set; }
        public Nullable<bool> AttendanceProcessStatus { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.Guid> Create_User { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.Guid> Edit_User { get; set; }
        public Nullable<System.DateTime> Edit_Date { get; set; }
    }
}
