//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Family_Business.WMGS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProcesedSalary
    {
        public int Id { get; set; }
        public string EID { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public Nullable<decimal> TotalWorkHour { get; set; }
        public Nullable<decimal> PayRate { get; set; }
        public Nullable<decimal> Total_Payment { get; set; }
        public Nullable<decimal> Benefits { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> Incentive { get; set; }
        public Nullable<System.Guid> Create_User { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.Guid> Edit_User { get; set; }
        public Nullable<System.DateTime> Edit_Date { get; set; }
    }
}
